name: Database Migration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create SQLite File
      run: touch database.sqlite
    
    - name: Migrate Database
      run: php migrate.php

    - name: Generate Fake Users
      run: php seed.php 1000
